name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-java@v3
        with: 
          distribution: 'adopt'
          java-version: '11'
      
      - uses: actions/setup-dotnet@v3
        # env:
        #   DOTNET_INSTALL_DIR: ${{ github.workspace }}
        with:
          dotnet-version: '7.0'

      - name: dotnet-ef        
        run: dotnet tool install --global dotnet-sonarscanner

      - name: run test
        run: |
          dotnet sonarscanner \
          begin /k:"Ilya-shzerban_sonar_AYmSDV5dCNZSiu4g55it" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"

          dotnet build

          dotnet sonarscanner \
          end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"